spring:
  profiles:
    active: jdbc
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

app:
  jwt:
#    secret: ${JWT_SECRET:gLHrOQzoOPsHp0kjwk46eYv58nNmygGckdMHR5jdJDg=}
    # Add new RSA configuration
    private-key-path: classpath:jwt-private.pem
    public-key-path: classpath:jwt-public.pem
    issuer: ${JWT_ISSUER:demo-app}
    expires-min: ${JWT_EXPIRES_MIN:30}
    audience: ${JWT_AUDIENCE:demo-api}