spring:
  profiles:
    active: jdbc
  datasource:
    url: jdbc:h2:mem:demo;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

app:
  jwt:
#    secret: ${JWT_SECRET:gLHrOQzoOPsHp0kjwk46eYv58nNmygGckdMHR5jdJDg=}
    # Add new RSA configuration
    private-key-path: classpath:jwt-private.pem
    public-key-path: classpath:jwt-public.pem
    issuer: ${JWT_ISSUER:demo-app}
    expires-min: ${JWT_EXPIRES_MIN:30}
    audience: ${JWT_AUDIENCE:demo-api}

# Logging configuration for understanding Spring Security
logging:
  level:
    # Enable debug logging for Spring Security to see filter chain
    org.springframework.security: DEBUG
    # Enable trace for even more detailed security information (optional)
    # org.springframework.security: TRACE
    # Show authentication and authorization decisions
    org.springframework.security.web.FilterChainProxy: DEBUG
    # Show JWT validation details
    org.springframework.security.oauth2: DEBUG
    # Application logging
    com.example.demo: INFO